port: 0
socks-port: 7891
mixed-port: 0
allow-lan: false
mode: rule
log-level: info

dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  enhanced-mode: fake-ip
  prefer-h3: false

  default-nameserver:
    - 127.0.0.53
    - 9.9.9.9

  nameserver:
    - https://xbox-dns.ru/dns-query

  nameserver-policy:
    "chatgpt.com": https://xbox-dns.ru/dns-query
    "*.chatgpt.com": https://xbox-dns.ru/dns-query
    "openai.com": https://xbox-dns.ru/dns-query
    "*.openai.com": https://xbox-dns.ru/dns-query

  fake-ip-range: 198.18.0.1/16

proxies:
  - name: corp-proxy
    type: http
    server: 192.168.0.10
    port: 3128

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - corp-proxy
      - DIRECT

rules:
  - MATCH,Proxy

ntp:
  enable: false