port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: debug

# If you use Clash.Meta/Mihomo, you can pin outbound to your USB NIC:
# interface-name: "enx1610c2d100e0"

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:1053

  # Public resolvers (no corporate DNS)
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8

  # DoH sent directly (not via any proxy)
  nameserver:
    - https://xbox-dns.ru/dns-query#CorpProxy
    # - https://cloudflare-dns.com/dns-query#DIRECT
    # - https://dns.google/dns-query#DIRECT

  # Use public DNS to resolve any upstreams (even though we have none here)
  proxy-server-nameserver:
    - 1.1.1.1
    - 8.8.8.8

  fake-ip-range: 198.18.0.1/16

# No upstream proxies — everything goes DIRECT via your system route (USB NIC)
proxies: []

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT

rules:
  # Keep private LAN ranges/direct loopback as DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT

  # Your internal domains stay DIRECT (may not resolve off corp LAN)
  - DOMAIN-SUFFIX,chelib.local,DIRECT
  - DOMAIN-SUFFIX,localnet,DIRECT
  - DOMAIN-SUFFIX,chelib.ru,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT

  - MATCH,Proxy