# Port for HTTP(S) proxy
port: 7890
# Port for SOCKS5 proxy
socks-port: 7891
# Allow LAN connections
allow-lan: true
# Clash mode
mode: rule
# Log level
log-level: info

# DNS configuration
dns:
  enable: true
  enhanced-mode: fake-ip
  listen: 127.0.0.1:1053
  # Force all DNS requests to go through Google's encrypted DNS service.
  nameserver:
    - https://dns.google/dns-query
  fake-ip-range: 198.18.0.1/16

# Proxy definitions
proxies:
  # Your organization's HTTP proxy
  - name: "OrgProxy"
    type: http
    server: proxy
    port: 3128

# Proxy groups for rule routing
proxy-groups:
  # Main selector to choose between your proxy and a direct connection
  - name: "Proxy"
    type: select
    proxies:
      - OrgProxy
      - DIRECT

# Traffic rules
rules:
  # Rule 1: Local network traffic should always go direct
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  
  # Rule 2: Your specific local domains go direct
  - DOMAIN-SUFFIX,chelib.local,DIRECT
  - DOMAIN-SUFFIX,chelib.ru,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT
  
  # Rule 3: Final catch-all rule. Everything else goes through your proxy.
  - MATCH,Proxy