port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: debug
# skip-cert-verify: false  # set true only if your corp proxy MITMs TLS and you can't install its root CA

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:1053

  default-nameserver:
    - 192.168.0.50
    - 192.168.0.55

  # Only this DoH upstream (via corporate proxy)
  nameserver:
    - https://xbox-dns.ru/dns-query#CorpProxy
    # - https://dns.google/dns-query#CorpProxy
    # - https://cloudflare-dns.com/dns-query#CorpProxy
  nameserver-policy:
    "geosite:private":
      - 192.168.0.50
      - 192.168.0.55
    "+.chelib.local":
      - 192.168.0.50
      - 192.168.0.55
    "+.localnet":
      - 192.168.0.50
      - 192.168.0.55
    "+.chelib.ru":
      - 192.168.0.50
      - 192.168.0.55

  proxy-server-nameserver:
    - system

  fake-ip-range: 198.18.0.1/16

proxies:
  - name: CorpProxy
    type: http
    server: 192.168.0.10
    port: 3128
    username: 'chelib.local\reader'
    password: ''

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - CorpProxy
      - DIRECT

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT

  - DOMAIN-SUFFIX,chelib.local,DIRECT
  - DOMAIN-SUFFIX,localnet,DIRECT
  - DOMAIN-SUFFIX,chelib.ru,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT

  - MATCH,Proxy